const locationHierarchy: Record<string, string[]> = {
    Adamawa: ["Banyo", "Martap", "Meiganga", "Ngaoundere", "Tibati"],
    Center: [
      "Akonolinga",
      "Bafia",
      "Makenene",
      "Mbalmayo",
      "Mbandjock",
      "Nkoteng",
      "Monatele",
      "Nanga Eboko",
      "Obala",
      "Sa'a",
      "Yaounde",
    ],
    East: [
      "Abong-Mbang",
      "Batouri",
      "Belabo",
      "Dimako",
      "Garoua-Boulai",
      "Lomie",
      "Mouloudou",
      "Yokadouma",
    ],
    "Far North": ["Kaele", "Kousseri", "Maroua", "Mokolo", "Mora", "Yagoua"],
    Littoral: [
      "Dizange",
      "Douala",
      "Edea",
      "Loum",
      "Manjo",
      "Melong",
      "Nkongsamba",
      "Penja",
    ],
    North: ["Garoua", "Guider"],
    "North West": [
      "Ako",
      "Bafut",
      "Bali",
      "Bambili",
      "Bamenda",
      "Batibo",
      "Fundong",
      "Kumbo",
      "Mbengwi",
      "Ndu",
      "Ndop",
      "Nkambe",
      "Santa",
      "Wum",
      "Nkwen",
    ],
    South: ["Ambam", "Campo", "Djoum", "Ebolowa", "Kribi", "Sangmelima"],
    "South West": [
      "Bangem",
      "Buea",
      "Eyumojock",
      "Fontem",
      "Idenau",
      "Kumba",
      "Limbe",
      "Mamfe",
      "Mbanga",
      "Menji",
      "Muyuka",
      "Mutengene",
      "Tiko",
    ],
    West: [
      "Bafang",
      "Bafoussam",
      "Bandjoun",
      "Dschang",
      "Foumban",
      "Foumbot",
      "Mbouda",
    ],
  };

  
  export { locationHierarchy };